DEFAULT_CHUNK_SIZE = 512
DEFAULT_CHUNK_OVERLAP = 50
DEFAULT_TOP_K = 5
DEFAULT_ALLOWED_ORIGINS = ["http://localhost:3000", "http://localhost:5173", "https://demoragassistant.web.app", "https://demoragassistant.firebaseapp.com"]
DEFAULT_EMBEDDING_MODEL = "text-embedding-3-small"
DEFAULT_VECTOR_STORE_PATH = "storage/vector_store"
DEFAULT_EMBEDDING_DIM = 1536
DEFAULT_CHAT_MODEL = "gpt-4o-mini"
DEFAULT_TEMPERATURE = 0.0
DEFAULT_CHAT_HISTORY_LIMIT = 3

DEFAULT_HOURLY_RATE_LIMIT = 10
DEFAULT_DAILY_RATE_LIMIT = 30
DEFAULT_GLOBAL_MONTHLY_LIMIT = 500
DEFAULT_COOLDOWN_SECONDS = 2
DEFAULT_MAX_TOKENS = 300
DEFAULT_MAX_QUERY_LENGTH = 500

DEFAULT_MAX_UPLOADS_PER_SESSION = 5
DEFAULT_MAX_FILE_SIZE_MB = 5
