import os
from dotenv import load_dotenv
from app.config import (
    DEFAULT_CHUNK_SIZE,
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_TOP_K,
    DEFAULT_ALLOWED_ORIGINS,
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_VECTOR_STORE_PATH,
    DEFAULT_EMBEDDING_DIM,
    DEFAULT_CHAT_MODEL,
    DEFAULT_TEMPERATURE,
    DEFAULT_CHAT_HISTORY_LIMIT,
    DEFAULT_HOURLY_RATE_LIMIT,
    DEFAULT_DAILY_RATE_LIMIT,
    DEFAULT_GLOBAL_MONTHLY_LIMIT,
    DEFAULT_COOLDOWN_SECONDS,
    DEFAULT_MAX_TOKENS,
    DEFAULT_MAX_QUERY_LENGTH,
    DEFAULT_MAX_UPLOADS_PER_SESSION,
    DEFAULT_MAX_FILE_SIZE_MB,
)

load_dotenv()

class Settings:
    def __init__(self):
        self.OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
        self.CHUNK_SIZE = int(os.getenv("CHUNK_SIZE", DEFAULT_CHUNK_SIZE))
        self.CHUNK_OVERLAP = int(os.getenv("CHUNK_OVERLAP", DEFAULT_CHUNK_OVERLAP))
        self.TOP_K = int(os.getenv("TOP_K", DEFAULT_TOP_K))
        self.ALLOWED_ORIGINS = os.getenv(
            "ALLOWED_ORIGINS", ",".join(DEFAULT_ALLOWED_ORIGINS)
        ).split(",")
        self.EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", DEFAULT_EMBEDDING_MODEL)
        self.VECTOR_STORE_PATH = os.getenv("VECTOR_STORE_PATH", DEFAULT_VECTOR_STORE_PATH)
        self.EMBEDDING_DIM = int(os.getenv("EMBEDDING_DIM", DEFAULT_EMBEDDING_DIM))
        self.CHAT_MODEL = os.getenv("CHAT_MODEL", DEFAULT_CHAT_MODEL)
        self.TEMPERATURE = float(os.getenv("TEMPERATURE", DEFAULT_TEMPERATURE))
        self.CHAT_HISTORY_LIMIT = int(os.getenv("CHAT_HISTORY_LIMIT", DEFAULT_CHAT_HISTORY_LIMIT))
        
        self.HOURLY_RATE_LIMIT = int(os.getenv("HOURLY_RATE_LIMIT", DEFAULT_HOURLY_RATE_LIMIT))
        self.DAILY_RATE_LIMIT = int(os.getenv("DAILY_RATE_LIMIT", DEFAULT_DAILY_RATE_LIMIT))
        self.GLOBAL_MONTHLY_LIMIT = int(os.getenv("GLOBAL_MONTHLY_LIMIT", DEFAULT_GLOBAL_MONTHLY_LIMIT))
        self.COOLDOWN_SECONDS = int(os.getenv("COOLDOWN_SECONDS", DEFAULT_COOLDOWN_SECONDS))
        self.MAX_TOKENS = int(os.getenv("MAX_TOKENS", DEFAULT_MAX_TOKENS))
        self.MAX_QUERY_LENGTH = int(os.getenv("MAX_QUERY_LENGTH", DEFAULT_MAX_QUERY_LENGTH))
        
        self.MAX_UPLOADS_PER_SESSION = int(os.getenv("MAX_UPLOADS_PER_SESSION", DEFAULT_MAX_UPLOADS_PER_SESSION))
        self.MAX_FILE_SIZE_MB = int(os.getenv("MAX_FILE_SIZE_MB", DEFAULT_MAX_FILE_SIZE_MB))

settings = Settings()
